@extends('layouts.public')
@section('title','BUMDes Berkah — Produk Lokal Moncongloe Lappara')
@section('body_class','home-page')
@section('content')
<section class="hero-home">
    <div class="hero-photo" aria-hidden="true"></div><div class="hero-shade" aria-hidden="true"></div>
    <div class="shell hero-content"><div class="eyebrow light"><span></span> Dari desa, untuk lebih banyak meja</div><h1>Produk lokal yang<br><em>punya cerita.</em></h1><p>Temukan kuliner, oleh-oleh, dan kerajinan dari UMKM Moncongloe Lappara — dikumpulkan dalam satu katalog BUMDes yang mudah diakses.</p><div class="hero-actions"><a class="button button-light" href="{{ route('catalogue') }}">Jelajahi Katalog <i class="bi bi-arrow-right"></i></a><a class="text-link light" href="#tentang">Kenal BUMDes Berkah <i class="bi bi-arrow-down"></i></a></div></div>
    <div class="hero-facts shell"><div><strong>{{ $totalProducts }}</strong><span>produk tercatat</span></div><div><strong>{{ $totalUmkm }}</strong><span>mitra UMKM aktif</span></div><div class="hero-note">Dikelola bersama untuk memperluas jangkauan usaha warga.</div></div>
</section>
<section class="section intro-section" id="tentang"><div class="shell intro-grid"><div><div class="eyebrow"><span></span>BUMDes Berkah</div><h2>Bukan sekadar etalase.<br>Ini jalan masuk ke usaha warga.</h2></div><div class="intro-copy"><p>BUMDes Berkah membantu produk-produk warga Moncongloe Lappara hadir lebih rapi, mudah ditemukan, dan lebih dekat dengan pembeli.</p><p>Katalog ini mempertahankan karakter tiap UMKM: siapa pembuatnya, apa produknya, bagaimana stoknya, dan bagaimana pembeli bisa memesan.</p><a class="text-link" href="{{ route('catalogue') }}">Lihat semua produk <i class="bi bi-arrow-right"></i></a></div></div></section>
<section class="section section-muted"><div class="shell"><div class="section-heading"><div><div class="eyebrow"><span></span>Pilihan terbaru</div><h2>Belanja dari yang<br>memang dibuat di sini.</h2></div><a class="outline-link" href="{{ route('catalogue') }}">Semua produk <i class="bi bi-arrow-right"></i></a></div><div class="product-grid">@forelse($featured as $product)<x-product-card :product="$product" />@empty<p>Belum ada produk.</p>@endforelse</div></div></section>
<section class="section categories-section"><div class="shell category-layout"><div class="category-copy"><div class="eyebrow"><span></span>Cari berdasarkan kebutuhan</div><h2>Tiga kelompok produk, satu desa yang aktif berkarya.</h2><p>Dari camilan hangat di Savala sampai kerajinan yang dikerjakan dengan tangan.</p></div><div class="category-list">@foreach($categories as $i=>$category)<a href="{{ route('catalogue',['kategori'=>$category->id]) }}"><span class="cat-index">0{{ $i+1 }}</span><span><strong>{{ $category->nama_kategori }}</strong><small>{{ $category->produk_count }} produk</small></span><i class="bi bi-arrow-up-right"></i></a>@endforeach</div></div></section>
<section class="section producers-section" id="mitra"><div class="shell"><div class="section-heading light"><div><div class="eyebrow light"><span></span>Wajah di balik produk</div><h2>Mitra UMKM yang<br>menghidupkan katalog.</h2></div><p>Setiap produk terhubung langsung dengan usaha yang memproduksinya.</p></div><div class="producer-grid">@foreach($producers as $producer)<article><div class="producer-number">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</div><h3>{{ $producer->nama_umkm }}</h3><p>{{ Str::limit($producer->deskripsi,110) }}</p><div><span>{{ $producer->pemilik }}</span><span>{{ $producer->produk_count }} produk</span></div></article>@endforeach</div></div></section>
<section class="section location-section"><div class="shell location-grid"><div class="location-card"><div class="eyebrow light"><span></span>Temukan kami</div><h2>Moncongloe Lappara,<br>Maros.</h2><p>Kawasan Kuliner Savana Lappara menjadi salah satu titik aktivitas UMKM dan kuliner warga.</p><a class="button button-light" href="https://maps.google.com/?q=Moncongloe+Lappara+Maros" target="_blank" rel="noopener">Buka Google Maps <i class="bi bi-geo-alt"></i></a></div><div class="map-art" aria-label="Ilustrasi lokasi Moncongloe Lappara"><div class="map-lines"></div><span class="map-pin"><i class="bi bi-geo-alt-fill"></i></span><strong>Moncongloe<br>Lappara</strong></div></div></section>
@endsection
