@extends('layouts.dashboard')
@section('title','Pesanan Saya') @section('eyebrow','Akun Pembeli') @section('page_title','Pesanan Saya')
@section('content')
<section class="dash-intro"><div><p class="eyebrow"><span></span>Riwayat belanja</p><h1>Pantau pesanan tanpa kehilangan detail.</h1><p>Status, pembayaran, nota, dan ulasan ada di satu tempat.</p></div><a class="button" href="{{ route('catalogue') }}"><i class="bi bi-plus-lg"></i> Belanja lagi</a></section>
<div class="metric-grid"><article><small>Total pesanan</small><strong>{{ $stats['total'] }}</strong><span>Semua transaksi</span></article><article><small>Menunggu</small><strong>{{ $stats['menunggu'] }}</strong><span>Perlu tindak lanjut</span></article><article><small>Diproses</small><strong>{{ $stats['diproses'] }}</strong><span>Sedang disiapkan</span></article><article><small>Selesai</small><strong>{{ $stats['selesai'] }}</strong><span>Sudah diterima</span></article></div>
<section class="data-panel"><div class="panel-heading"><div><small>PESANAN TERBARU</small><h2>Riwayat transaksi</h2></div></div>
@if($orders->count())<div class="order-stack">@foreach($orders as $order)<article class="buyer-order"><div class="buyer-order-top"><div><small>#{{ str_pad($order->id,5,'0',STR_PAD_LEFT) }} · {{ optional($order->tanggal_pesan)->format('d M Y, H:i') }}@if($order->batch_keroyokan_id) · <b style="color:var(--green-800)">🤝 Keroyokan #KR-{{ str_pad($order->batch_keroyokan_id,5,'0',STR_PAD_LEFT) }}</b>@endif</small><h3>{{ $order->produk->nama_produk }}</h3><p>{{ $order->produk->umkm->nama_umkm }} · {{ $order->jumlah }} item</p></div><x-status-badge :status="$order->status"/></div>@if($order->produk && $order->produk->stok_status === 'Pre-Order')<div style="background: #eff6ff; border: 1px solid #bfdbfe; color: #1e40af; border-radius: 8px; padding: 10px 14px; margin: 10px 0; font-size: 12px; display: flex; align-items: center; gap: 8px;"><i class="bi bi-truck" style="font-size: 16px; color: #3b82f6;"></i><span><strong>Informasi Pre-Order:</strong> Barang ini akan dikirim sesuai estimasi skala yang diberikan penjual yaitu <strong>{{ $order->produk->estimasi_po_hari ? $order->produk->estimasi_po_hari . ' Hari' : 'PO' }}</strong> sejak tanggal pesan @if($order->tanggal_pesan && $order->produk->estimasi_po_hari) (estimasi kirim: <strong>{{ \Carbon\Carbon::parse($order->tanggal_pesan)->addDays($order->produk->estimasi_po_hari)->translatedFormat('d M Y') }}</strong>)@endif.</span></div>@endif<div class="buyer-order-meta"><span>Metode <b>{{ $order->metode_pembayaran }}</b></span><span>Total <b>Rp{{ number_format((float)$order->total_harga,0,',','.') }}</b></span><span>Tujuan <b>{{ $order->alamat_pengiriman ?: '-' }}</b></span></div>@if($order->metode_pembayaran === 'Transfer' && $order->rekening_bank_snapshot)<div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 14px; margin: 10px 0; font-size: 12px; display: flex; align-items: center; justify-content: space-between;"><div><span style="color: #64748b; font-weight: 600; display: block;">Rekening Tujuan Transfer (Platform):</span><strong style="color: #0f172a; font-size: 13px;">{{ $order->rekening_bank_snapshot }}</strong></div><button type="button" class="btn-secondary" style="padding: 4px 8px; font-size: 11px;" onclick="navigator.clipboard.writeText('{{ $order->rekening_bank_snapshot }}'); this.innerText='Tersalin!'; setTimeout(()=>this.innerText='Salin', 2000)"><i class="bi bi-copy"></i> Salin</button></div>@endif<div class="row-actions"><a class="btn-secondary" href="{{ route('receipt.show',$order) }}" target="_blank"><i class="bi bi-printer"></i> Nota</a>
@if($order->status==='Menunggu')<form method="post" action="{{ route('buyer.orders.cancel',$order) }}" onsubmit="return confirm('Batalkan pesanan ini?')">@csrf @method('PATCH')<button class="btn-danger">Batalkan</button></form>@endif
@if(in_array($order->metode_pembayaran,['Transfer','QRIS']) && $order->status!=='Dibatalkan')<form class="proof-form" method="post" enctype="multipart/form-data" action="{{ route('buyer.orders.proof',$order) }}">@csrf<label class="btn-secondary"><i class="bi bi-upload"></i> {{ $order->bukti_pembayaran?'Ganti bukti':'Upload bukti' }}<input type="file" name="bukti_pembayaran" accept="image/jpeg,image/png,image/webp" onchange="const f = this.files[0]; if (f && f.size > 5 * 1024 * 1024) { alert('Ukuran foto terlalu besar (' + (f.size / (1024*1024)).toFixed(1) + ' MB). Maksimal ukuran bukti pembayaran adalah 5 MB.'); this.value = ''; return false; } this.form.submit();"></label></form>@endif
@if($order->status==='Selesai' && !$order->ulasan)<button class="btn-primary" type="button" data-review-open="review-{{ $order->id }}"><i class="bi bi-star"></i> Beri ulasan</button>@elseif($order->ulasan)<span class="review-done"><i class="bi bi-star-fill"></i> {{ $order->ulasan->rating }}/5</span>@endif</div>
@if($order->status==='Selesai' && !$order->ulasan)<dialog id="review-{{ $order->id }}" class="review-dialog"><form method="post" action="{{ route('buyer.orders.review',$order) }}">@csrf<div class="dialog-head"><div><small>ULAS PRODUK</small><h3>{{ $order->produk->nama_produk }}</h3></div><button type="button" data-review-close="review-{{ $order->id }}">×</button></div><label>Rating<select name="rating" required><option value="5">5 — Sangat puas</option><option value="4">4 — Puas</option><option value="3">3 — Cukup</option><option value="2">2 — Kurang</option><option value="1">1 — Tidak puas</option></select></label><label>Komentar<textarea name="komentar" rows="4" placeholder="Ceritakan pengalaman Anda..."></textarea></label><button class="button wide">Kirim ulasan</button></form></dialog>@endif
</article>@endforeach</div><div class="pagination-wrap">{{ $orders->links() }}</div>@else<x-empty-state title="Belum ada pesanan" text="Katalog UMKM lokal sudah siap dijelajahi."/>@endif</section>
@endsection
