<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Dashboard') — LUDES-MARKET</title>
<link rel="icon" type="image/png" href="{{ asset('assets/img/favicon-32x32.png') }}"><link rel="apple-touch-icon" href="{{ asset('assets/img/apple-touch-icon.png') }}">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('assets/css/app.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/dashboard.css') }}">@stack('head')</head>
<body class="dashboard-body"><div class="dashboard-shell">
<aside class="dashboard-sidebar" data-sidebar><div class="sidebar-brand"><a class="brand" href="{{ route('home') }}"><img src="{{ asset('assets/img/logo-mark.png') }}" alt="Logo LUDES-MARKET" class="brand-mark"><span><b>LUDES</b>-MARKET<small>Moncongloe Lappara</small></span></a><button type="button" data-sidebar-close aria-label="Tutup menu"><i class="bi bi-x-lg"></i></button></div>
<div class="sidebar-context"><small>Ruang kerja</small><strong>{{ auth()->user()->isAdmin()?'Administrator':(auth()->user()->isSeller()?'Mitra UMKM':'Pembeli') }}</strong></div>
<nav class="sidebar-nav">
@if(auth()->user()->isAdmin())
<a class="{{ request()->routeIs('admin.dashboard')?'active':'' }}" href="{{ route('admin.dashboard') }}"><i class="bi bi-grid"></i>Ringkasan</a><a class="{{ request()->routeIs('admin.verifikasi-penjual.*')?'active':'' }}" href="{{ route('admin.verifikasi-penjual.index') }}"><i class="bi bi-person-check-fill"></i>Verifikasi Penjual</a><a class="{{ request()->routeIs('admin.disbursement.*')?'active':'' }}" href="{{ route('admin.disbursement.index') }}"><i class="bi bi-wallet2"></i>Pencairan UMKM</a><a class="{{ request()->routeIs('admin.zona-pengiriman.*')?'active':'' }}" href="{{ route('admin.zona-pengiriman.index') }}"><i class="bi bi-truck"></i>Zona Pengiriman</a><a class="{{ request()->routeIs('admin.umkm.*') && !request()->routeIs('admin.umkm.analytics*')?'active':'' }}" href="{{ route('admin.umkm.index') }}"><i class="bi bi-shop"></i>UMKM</a><a class="{{ request()->routeIs('admin.products.*')?'active':'' }}" href="{{ route('admin.products.index') }}"><i class="bi bi-box-seam"></i>Produk</a><a class="{{ request()->routeIs('admin.keroyokan.*')?'active':'' }}" href="{{ route('admin.keroyokan.index') }}"><i class="bi bi-people-fill"></i>Keroyokan</a><a class="{{ request()->routeIs('admin.rekening-bank.*')?'active':'' }}" href="{{ route('admin.rekening-bank.index') }}"><i class="bi bi-bank"></i>Rekening Bank</a><a class="{{ request()->routeIs('admin.users.*')?'active':'' }}" href="{{ route('admin.users.index') }}"><i class="bi bi-people"></i>Pengguna</a><a class="{{ request()->routeIs('admin.orders.*')?'active':'' }}" href="{{ route('admin.orders.index') }}"><i class="bi bi-receipt"></i>Pesanan</a><a class="{{ request()->routeIs('admin.reports.*')?'active':'' }}" href="{{ route('admin.reports.index') }}"><i class="bi bi-bar-chart"></i>Laporan</a><a class="{{ request()->routeIs('admin.umkm.analytics*')?'active':'' }}" href="{{ route('admin.umkm.analytics') }}"><i class="bi bi-bar-chart-line"></i>Analitik UMKM</a><a class="{{ request()->routeIs('admin.logs.*')?'active':'' }}" href="{{ route('admin.logs.index') }}"><i class="bi bi-clock-history"></i>Aktivitas</a>
@elseif(auth()->user()->isSeller())
<a class="{{ request()->routeIs('seller.dashboard')?'active':'' }}" href="{{ route('seller.dashboard') }}"><i class="bi bi-grid"></i>Ringkasan</a><a class="{{ request()->routeIs('seller.profile.*')?'active':'' }}" href="{{ route('seller.profile.edit') }}"><i class="bi bi-shop"></i>Profil & Akun</a><a class="{{ request()->routeIs('seller.products.*')?'active':'' }}" href="{{ route('seller.products.index') }}"><i class="bi bi-box-seam"></i>Produk</a><a class="{{ request()->routeIs('seller.orders.*')?'active':'' }}" href="{{ route('seller.orders.index') }}"><i class="bi bi-receipt"></i>Pesanan</a><a class="{{ request()->routeIs('seller.reports.*')?'active':'' }}" href="{{ route('seller.reports.index') }}"><i class="bi bi-bar-chart"></i>Laporan</a><a class="{{ request()->routeIs('seller.analytics*')?'active':'' }}" href="{{ route('seller.analytics') }}"><i class="bi bi-graph-up-arrow"></i>Analitik Usaha</a>
@else
<a class="{{ request()->routeIs('buyer.dashboard')?'active':'' }}" href="{{ route('buyer.dashboard') }}"><i class="bi bi-bag-check"></i>Pesanan Saya</a><a class="{{ request()->routeIs('buyer.profile.*')?'active':'' }}" href="{{ route('buyer.profile.edit') }}"><i class="bi bi-person-gear"></i>Pengaturan Akun</a><a href="{{ route('catalogue') }}"><i class="bi bi-compass"></i>Belanja Produk</a><a href="{{ route('cart.index') }}"><i class="bi bi-bag"></i>Keranjang</a>
@endif
</nav><div class="sidebar-bottom"><a href="{{ route('home') }}"><i class="bi bi-arrow-left"></i>Lihat situs</a><form method="post" action="{{ route('logout') }}">@csrf<button><i class="bi bi-box-arrow-right"></i>Keluar</button></form></div></aside>
<div class="sidebar-backdrop" data-sidebar-backdrop></div><main class="dashboard-main"><header class="dashboard-topbar"><button class="sidebar-trigger" data-sidebar-open aria-label="Buka menu"><i class="bi bi-list"></i></button><div><small>@yield('eyebrow','LUDES-MARKET')</small><strong>@yield('page_title','Dashboard')</strong></div><a class="topbar-user" href="{{ auth()->user()->isSeller() ? route('seller.profile.edit') : (auth()->user()->isBuyer() ? route('buyer.profile.edit') : route('admin.dashboard')) }}" style="text-decoration:none;color:inherit;" title="Buka pengaturan profil"><span>{{ strtoupper(substr(auth()->user()->nama_lengkap,0,1)) }}</span><div><b>{{ auth()->user()->nama_lengkap }}</b><small>{{ ucfirst(auth()->user()->role) }}</small></div></a></header><div class="dashboard-content"><x-flash/>@yield('content')</div></main></div><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script><script src="{{ asset('assets/js/app.js') }}"></script><script src="{{ asset('assets/js/dashboard.js') }}"></script>@if(auth()->check() && auth()->user()->isSeller())<script src="{{ asset('assets/js/seller-notifications.js') }}"></script>@endif @stack('scripts')</body></html>
